version: '3.8'

services:
  # Serviço da aplicação Spring Boot
  app:
    image: demo-spring-boot # Nome da imagem do Docker que você criou anteriormente
    build:
      context: .
    ports:
      - "8081:8081"  # Expondo a porta 8081 para a aplicação Spring Boot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/riven
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT-SQL=true
    depends_on:
      - db  # Garante que o PostgreSQL será iniciado antes do Spring Boot

  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: riven
    ports:
      - "5432:5432"  # Expondo a porta 5432 para o banco de dados
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistência de dados

volumes:
  postgres-data:
    driver: local
