version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: banco_de_dados
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: riven
    ports:
      - "5435:5432"  # Change the host port to 5433

  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_APPLICATION_NAME: demo
      DB_URL: jdbc:postgresql://postgres:5433/riven  # Change the port to 5433
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root